### PR TITLE
Fixes #246

### LINKED ISSUE #246: CancelJobs with empty version
The following call is not getting flagged as an invalid version:

    cancelJobs.cancelJob(jobname, jobid, "")

CancelJobs is only picking up version=null or an incorrect version string, not an empty string in cancelJobsCommon().

Additionally, when an invalid version is found, it should throw a IllegalArgumentException, not a generic Exception.

### PR DESCRIPTION
**Pull request by corinned**
Signed-off-by: Corinne DeStefano <corinne.destefano@broadcom.com>

### CODE REVIEW

**Review by frankgiordano — APPROVED** [review]
approved

**Comment by corinned** [comment]
Looks like DeleteJobs has the same issue.  I'll make that fix and push it to this PR as well.

**Comment by frankgiordano** [comment]
ok

**Comment by frankgiordano** [comment]
looks good.

**Pull request merged**
