### PR TITLE
some initial work for listing datasets and datasetmembers

### PR DESCRIPTION
**Pull request by Nike682631**

### CODE REVIEW

**Comment by Nike682631** [comment]
@Nurkambay @frankgiordano this pr is not complete yet please do not merge it. I've created it so that both of you could review this code and verify if I'm going in the right direction.

**Comment by frankgiordano** [comment]
@Nurkambay Thanks for the PR! I will try to review. BTW going forward if your PR is not ready not, create a draft PR.

**Comment by frankgiordano** [comment]
I reviewed your PR. I am wondering where did you get variables names for dataset.java? I searched the zowe-cli packages and code wise I see the following https://github.com/zowe/zowe-cli/blob/master/packages/zosfiles/src/doc/IDataSet.ts but it is not the same content you created.

**Comment by Nike682631** [comment]
> @Nurkambay Thanks for the PR! I will try to review. BTW going forward if your PR is not ready yet, create a draft PR.

If I create a draft pr I cannot request other people to review.

**Comment by Nike682631** [comment]
> I reviewed your PR. I am wondering where did you get variables names for dataset.java? I searched the zowe-cli packages and code wise I see the following https://github.com/zowe/zowe-cli/blob/master/packages/zosfiles/src/doc/IDataSet.ts but it is not the same content you created.
@frankgiordano @Nurkambay 
I got the variable names from here. https://github.com/zowe/zowe-client-kotlin-sdk/blob/main/src/main/kotlin/eu/ibagroup/r2z/Dataset.kt
I followed making this dataset file the same way https://github.com/zowe/zowe-client-java-sdk/blob/main/src/main/java/zosjobs/response/Job.java was defined and had a similar way of being defined in https://github.com/zowe/zowe-client-kotlin-sdk/blob/main/src/main/kotlin/eu/ibagroup/r2z/JobStatus.kt
Please verify if I'm going right.

**Comment by frankgiordano** [comment]
I see. I think it is best to follow the NodeJS zowe-cli structure than kotlin. That is what I am doing and all the code in place is following that. So best to keep the code in same style. see https://github.com/zowe/zowe-cli/blob/7aeba32e4b773b81d94fd88729eb55773034974d/packages/zosfiles/src/methods/list/doc/IZosmfListResponse.ts

**Comment by Nike682631** [comment]
Sure I'll remove if there are any other variables in the code from the
kotlin one.

**Comment by frankgiordano** [comment]
BTW in create PR screen I can add a reviewer before creating a PR and then I can select draft PR and create it that way and now I have a draft PR with a reviewer assigned..

**Comment by Nike682631** [comment]
@frankgiordano @Nurkambay I'm not sure how i need to proceed here. Can you maybe link the files in the nodejs cli structure as a reference.

**Comment by Nike682631** [comment]
> @frankgiordano @Nurkambay I'm not sure how i need to proceed here. Can you maybe link the files in the nodejs cli structure as a reference.

nevermind got it

**Comment by Nike682631** [comment]
I wanted to ask this @frankgiordano @Nurkambay. The current project structure is different in nodejs cli , java sdk and other sdk's.
Shall we redesign the project structure to match the one in node js cli?? I can do that but need your 👍🏽 before that.

**Comment by frankgiordano** [comment]
I am following the nodeJS directory structure almost entirely the same except using the 'doc' directory. I did not use it and put those items in doc directory in the root component package directory..

**Review by Nurkambay — APPROVED** [review]
LGTM!

**Pull request merged**
